services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Client service
    Phillarmonic\SyncopateBundle\Client\SyncopateClient:
        arguments:
            $httpClient: '@http_client'
            $baseUrl: '%phillarmonic_syncopate.base_url%'
            $defaultOptions:
                timeout: '%phillarmonic_syncopate.timeout%'
                max_retries: '%phillarmonic_syncopate.max_retries%'
                retry_delay: '%phillarmonic_syncopate.retry_delay%'
        public: true

    # Entity type registry service
    Phillarmonic\SyncopateBundle\Service\EntityTypeRegistry:
        arguments:
            $entityPaths: '%phillarmonic_syncopate.entity_paths%'
            $autoCreateEntityTypes: '%phillarmonic_syncopate.auto_create_entity_types%'
            $cacheEntityTypes: '%phillarmonic_syncopate.cache_entity_types%'
            $cacheTtl: '%phillarmonic_syncopate.cache_ttl%'
        calls:
            - [initialize, []]

    # Main service for interacting with SyncopateDB
    Phillarmonic\SyncopateBundle\Service\SyncopateService:
        arguments:
            $client: '@Phillarmonic\SyncopateBundle\Client\SyncopateClient'
            $entityTypeRegistry: '@Phillarmonic\SyncopateBundle\Service\EntityTypeRegistry'
        public: true

    # Entity mapper
    Phillarmonic\SyncopateBundle\Mapper\EntityMapper:
        public: false

    # Repository factory
    Phillarmonic\SyncopateBundle\Repository\EntityRepositoryFactory:
        arguments:
            $syncopateService: '@Phillarmonic\SyncopateBundle\Service\SyncopateService'
            $entityMapper: '@Phillarmonic\SyncopateBundle\Mapper\EntityMapper'
        public: true

    # Register the controller if enabled
    Phillarmonic\SyncopateBundle\Controller\SyncopateProxyController:
        public: true
        tags: ['controller.service_arguments']