services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Client service
    Phillarmonic\SyncopateBundle\Client\SyncopateClient:
        arguments:
            $httpClient: '@syncopate_http_client'
            $baseUrl: '%phillarmonic_syncopate.base_url%'
            $defaultOptions:
                timeout: '%phillarmonic_syncopate.timeout%'
        public: true

    # Http client with retry capability
    syncopate_http_client:
        class: Symfony\Component\HttpClient\RetryableHttpClient
        arguments:
            $client: '@http_client'
            $strategy: '@syncopate_retry_strategy'
            $maxRetries: '%phillarmonic_syncopate.max_retries%'

    # Retry strategy for an http client
    syncopate_retry_strategy:
        class: Symfony\Component\HttpClient\Retry\GenericRetryStrategy
        arguments:
            - [0, 423, 425, 429, 500, 502, 503, 504, 507, 510]  # $statusCodes
            - [0, 2, 3]                                          # $methodsToRetry
            - '%phillarmonic_syncopate.retry_delay%'            # $delayMs
            - 2                                                  # $multiplier
            - 60000                                              # $maxDelayMs

    # Entity type registry service
    Phillarmonic\SyncopateBundle\Service\EntityTypeRegistry:
        arguments:
            $entityPaths: '%phillarmonic_syncopate.entity_paths%'
            $autoCreateEntityTypes: '%phillarmonic_syncopate.auto_create_entity_types%'
            $cacheEntityTypes: '%phillarmonic_syncopate.cache_entity_types%'
            $cacheTtl: '%phillarmonic_syncopate.cache_ttl%'
        calls:
            - [initialize, []]

    # Main service for interacting with SyncopateDB
    Phillarmonic\SyncopateBundle\Service\SyncopateService:
        arguments:
            $client: '@Phillarmonic\SyncopateBundle\Client\SyncopateClient'
            $entityTypeRegistry: '@Phillarmonic\SyncopateBundle\Service\EntityTypeRegistry'
        public: true

    # Entity mapper
    Phillarmonic\SyncopateBundle\Mapper\EntityMapper:
        public: false

    # Repository factory
    Phillarmonic\SyncopateBundle\Repository\EntityRepositoryFactory:
        arguments:
            $syncopateService: '@Phillarmonic\SyncopateBundle\Service\SyncopateService'
            $entityMapper: '@Phillarmonic\SyncopateBundle\Mapper\EntityMapper'
        public: true